/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as Auth403IndexRouteImport } from './routes/_auth/403/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Auth403IndexRoute = Auth403IndexRouteImport.update({
  id: '/403/',
  path: '/403/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/403/': typeof Auth403IndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404IndexRoute
  '/login': typeof LoginIndexRoute
  '/403': typeof Auth403IndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/users': typeof AuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/403/': typeof Auth403IndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404/'
    | '/login/'
    | '/403/'
    | '/dashboard/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/login' | '/403' | '/dashboard' | '/settings' | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/404/'
    | '/login/'
    | '/_auth/403/'
    | '/_auth/dashboard/'
    | '/_auth/settings/'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  R404IndexRoute: typeof R404IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404/'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/403/': {
      id: '/_auth/403/'
      path: '/403'
      fullPath: '/403/'
      preLoaderRoute: typeof Auth403IndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  Auth403IndexRoute: typeof Auth403IndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  Auth403IndexRoute: Auth403IndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  R404IndexRoute: R404IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
